import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
    suppressHydrationWarning
    >
      <body
        className={'antialiased flex flex-col min-h-screen'}
      >
        <Header />
        <main className="flex-grow">{children}</main>
        <footer className="p-4 bg-gray-800 text-white text-center">
          footer
        </footer>
      </body>
    </html>
  );
}
